apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdk8s
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: snkarhale/cicdk8s:cicdk8simg.new
        ports:
        - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: cicdk8s service
spec:
  selector:
    app: python
  ports:
  - protocol: TCP
    port: 8761
    nodePort: 32321
  type: NodePort

